add missing 'CODE: ' for testServerSelfConflict
Otherwise you will encounter this exception:
  RuntimeError: "testServerSelfConflict needs exactly one code"

Signed-off-by: Jianhong Yin <jiyin@redhat.com>
Signed-off-by: J. Bruce Fields <bfields@redhat.com>